# configures three k3s ConfigMaps
# we inject web pages into pods as configuration files.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>App 1</title>
        <style>body { background-color: #F58427; color: white; text-align: center; padding-top: 50px; font-family: sans-serif; }</style>
    </head>
    <body>
        <h1>KUBERNETES : Hello from app1.</h1>
    </body>
    </html>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>App 2</title>
        <style>body { background-color: #27F549; color: white; text-align: center; padding-top: 50px; font-family: sans-serif; }</style>
    </head>
    <body>
        <h1>KUBERNETES : Hello from app2.</h1>
    </body>
    </html>
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app3
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>App 3</title>
        <style>body { background-color: #F527E0; color: white; text-align: center; padding-top: 50px; font-family: sans-serif; }</style>
    </head>
    <body>
        <h1>KUBERNETES : Hello from app3.</h1>
    </body>
    </html> 
