apiVersion: apps/v1
kind: Deployment
metadata:
  name: wilplayground-deployment
spec:
  selector:
    matchLabels:
      app: wilplayground
  template:
    metadata:
      labels:
        app: wilplayground
    spec:
      containers:
      - name: wilplayground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888